### ISSUE TITLE
in lens errors if path doesn't exist

### ISSUE THREAD

**Issue by JacCas2014** [ctford/traversy#13]
Test:
(-> {:fo 1} (lens/view-single (lens/in [:foo])))

returns:
AssertionError Assert failed: Found 0 foci, but expected exactly 1.
(= 1 quantity)

**Comment by johncowie** [comment]
Hi @JacCas2014, this behaviour is intentional.  It allows cases where a path is present but the value is `nil` to be distinguished from cases where the path isn't present.

One possibility would be adding an additional optional argument to `view-single` to specify a default value if no values are found.  E.g. 
```clojure
(-> {} (lens/view-single (lens/in [:foo]) "No value")) => "No value"
```

Would that be helpful?  Alternatively, to return `nil` instead of getting an error, you can use `view` instead and then take the first item from the values found:

```clojure
(-> {:foo 1} (lens/view (lens/in [:foo])) first) => 1
(-> {:fo 1} (lens/view (lens/in [:foo])) first) => nil
```

**Comment by JacCas2014** [comment]
Thanks, figured there must be a good reason for changing it. After looking at our code there are only a couple of occurences where it's breaking things, so will just change these to use view and first. Feel free to close this, but if you feel like making that change to view-single in future that would be cool too.  Thanks for your help

**Comment by johncowie** [comment]
👍 

Actually, just remembered that the `in` lens already supports supply a not-found argument.

So another option is:
```clojure
(-> {:fo 1} (lens/view-single (lens/in [:foo] nil))) => nil
```
This might work better for you if you're composing your `in` lens with others.

Will close this and raise a separate issue for that view-single feature, that migh still be a handy thing to have.

**Comment by JacCas2014** [comment]
Thanks. Just realised `in` won't work in the scenario of combined lenses like the following:
`(-> {:fo 1} (lens/view-single (lens/*> (lens/in [:too] nil) lens/all-values (lens/in [:foo] nil))))`

Unless I've missed something... 

Thanks for your help

**Comment by johncowie** [comment]
Ah yes in that example it'll return a collection of nils. Ok that's a good supporting data point to the case for adding that optional arg to view-single.

**Comment by JacCas2014** [comment]
:+1: Thanks
